name: talan_tools
description: A collection of asorted utils for flutter development
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: lib/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
