name: turnotron
description: A tool for managing working hours
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  absence_api:
    path: packages/absence_api
  absence_repository:
    path: packages/absence_repository
  authentication_api:
    path: 'packages/authentication_api'
  authentication_repository:
    path: 'packages/authentication_repository'
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  calendar_date_picker2: ^0.5.3
  date_field: ^4.0.1
  dio: ^5.3.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  http_absence_api:
    path: packages/http_absence_api
  http_authentication_api:
    path: packages/http_authentication_api
  http_office_api:
    path: packages/http_office_api
  http_schedule_api:
    path: packages/http_schedule_api
  http_user_api:
    path: packages/http_user_api
  image_picker: ^1.0.1
  intl: ^0.18.0
  just_the_tooltip: ^0.0.12
  multi_select_flutter: ^4.1.3
  office_api:
    path: packages/office_api
  office_repository:
    path: packages/office_repository
  overlay_support: ^2.1.0
  preferences_api:
    path: 'packages/preferences_api'
  preferences_repository:
    path: 'packages/preferences_repository'
  provider: ^6.0.5
  rename: ^2.1.1
  responsive_framework: ^1.1.0
  schedule_api:
    path: packages/schedule_api
  schedule_repository:
    path: packages/schedule_repository
  secure_preferences_api:
    path: 'packages/secure_preferences_api'
  table_calendar: ^3.0.9
  talan_tools:
    path: packages/talan_tools
  universal_html: ^2.2.3
  url_launcher: ^6.1.12
  url_strategy: ^0.2.0
  user_api:
    path: packages/user_api
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/img/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: packages/talan_tools/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: packages/talan_tools/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: packages/talan_tools/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: packages/talan_tools/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: packages/talan_tools/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: packages/talan_tools/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: packages/talan_tools/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: packages/talan_tools/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: packages/talan_tools/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: packages/talan_tools/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: packages/talan_tools/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
