name: secure_preferences_api
description: A flutter implementation of preferences_api using flutter_secure_storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  preferences_api:
    path: '../preferences_api'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
