name: schedule_api
description: Interface and models for an API providing management access to schedules
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  absence_api:
    path: '../absence_api'
  common_models_repository:
    path: '../common_models_repository'
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
